import type { Metadata } from "next";
import "./styles/main.scss";
// import Provi
export const metadata: Metadata = {
  title: "Weather or not",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">{children}</html>;
}
